### ISSUE TITLE
Что за данные ?

### ISSUE THREAD

**Issue by envery** [kogdaobed/ARIMA-inflation#1]
Привет , среднюю по каким данным считаешь ? что за датасет ?  питон очень удобен в подобных штуках, еще недавно друг рассказывал, как чат-гпт ему скрипты писал )

**Comment by kogdaobed** [comment]
привет 
https://rosstat.gov.ru/statistics/price (Индексы потребительских цен на товары и услуги по Российской Федерации, месяцы (с 1991 г.) 1.1 Индексы потребительских цен на товары и услуги по Российской Федерации в 1991-2023 гг.) инфляция = ипц - 100

**Comment by envery** [comment]
думаю с текущим движем в мировой экономике, придется учитывать поправки на ветер, но удивительно на сколько быстрей и лучше людей машины считают числа. 
python крут )

**Comment by kogdaobed** [comment]
в принципе просто арима не подходит для прогноза инфляции или про что вы. ипц именно и является показателем инфляции..... но наверно надо брать для прогноза всякие другие показатели, строя сариму или саримакс, но для моей цели это пока что не требуется 
спасибо за внимания к моей работе!

**Comment by envery** [comment]
фин. рынки это мощно, там от средних часто отскоки идут, но много сторонних событий еще. А узнавать будущее это чуть ли не магия. 
Какая цель если не секрет ?
да не за что, на hh у тебя все скрыто, кроме гита.

**Comment by kogdaobed** [comment]
вк @kogdaobed 
тг @bs_sbwnnsndn  
цель расширить свои навыки и знания. да почему магия, бывают такие данные, по которым внутривыборочные прогнозы строятся довольно неплохие, все же упирается в данные и знания, последние пока не позволяют развернуться
ну то есть вот я попыталась сделать это не так как делала обычно (не с помощью эконометрических пакетов оценить авторегрессию)
